/*
 * swarm_message_types.h
 *
 *  Created on: May 31, 2023
 *      Author: kiraly
 */

#ifndef SWARM_SWARM_MESSAGE_TYPES_H_
#define SWARM_SWARM_MESSAGE_TYPES_H_

typedef enum
{
	SWARM_MESSAGE_HANDSHAKE,
	SWARM_MESSAGE_KEEP_ALIVE,
	SWARM_MESSAGE_CHOKE,
	SWARM_MESSAGE_UNCHOKE,
	SWARM_MESSAGE_INTERESTED,
	SWARM_MESSAGE_NOT_INTERESTED,
	SWARM_MESSAGE_HAVE,
	SWARM_MESSAGE_BITFIELD,
	SWARM_MESSAGE_REQUEST,
	SWARM_MESSAGE_PIECE,
	SWARM_MESSAGE_CANCEL,
	SWARM_MESSAGE_PORT
} swarm_message_e;

#endif /* SWARM_SWARM_MESSAGE_TYPES_H_ */
